@set allusersprofile=c:\programdata
@set appdata=c:\users\coolie\appdata\roaming
@set baseclasses=h:\dev\directshow\directshow_vc2005\microsoft sdks\windows\v7.1\samples\multimedia\directshow\baseclasses
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=new-dev-pc
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=v:\apps\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set dxsdk_dir=v:\dx90sdk\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\
@set homedrive=c:
@set homepath=\users\coolie
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set include=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\include;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um;c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.19041.0\shared;c:\program files (x86)\windows kits\10\include\10.0.19041.0\um;c:\program files (x86)\windows kits\10\include\10.0.19041.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.19041.0\cppwinrt
@set lib=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\lib\x86;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.19041.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.19041.0\um\x86
@set libpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\lib\x86;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.19041.0;c:\program files (x86)\windows kits\10\references\10.0.19041.0;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\coolie\appdata\local
@set logonserver=\\new-dev-pc
@set macrium_987_aes=0
@set macrium_987_backup_type=0
@set macrium_987_compression=1
@set macrium_987_directory=x:\10img\
@set macrium_987_drive_partition1=1, 0
@set macrium_987_drive_partition2=1, 3
@set macrium_987_filename1=2fc26e5cec1365fd-00-00.mrimg
@set macrium_987_filepath1=x:\10img\2fc26e5cec1365fd-00-00.mrimg
@set macrium_987_imageid=2fc26e5cec1365fd
@set macrium_987_increment1=0
@set macrium_987_intelligent=1
@set macrium_987_maxfilesize=500
@set macrium_987_method=0
@set macrium_987_method1=0
@set macrium_987_password=0
@set macrium_prefix=macrium_987
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=v:\apps\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=8
@set onedrive=c:\users\coolie\onedrive
@set openssl_conf=v:\steve\mydocs\openssl-win64\bin\openssl.cfg
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\\extensions\microsoft\intellicode\cli;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\bin\hostx86\x86;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\;c:\program files (x86)\windows kits\10\bin\10.0.19041.0\x86;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\bin\hostx86\x86;c:\program files (x86)\windows kits\10\bin\10.0.19041.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\debugging tools for windows (x64)\;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\putty\;c:\program files (x86)\microsoft sql server\90\tools\binn\;c:\nasm\;c:\program files (x86)\windows live\shared;v:\steve\mydocs\openssl-win64\bin;c:\windows\system32\openssh\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files\microsoft windows performance toolkit\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\crucial\crucial storage executive;c:\llvm\bin;c:\program files\microsoft\web platform installer\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\git\cmd;c:\program files\cmake\bin;c:\program files\dotnet\;c:\users\coolie\appdata\local\microsoft\windowsapps;c:\program files (x86)\windows kits\10\debuggers;c:\program files (x86)\dr. memory\bin\;c:\users\coolie\appdata\local\programs\fiddler;c:\users\coolie\appdata\local\microsoft\windowsapps;c:\users\coolie\appdata\local\programs\python\python36;c:\users\coolie\.dotnet\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\linux\bin\connectionmanagerexe
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\coolie\appdata\local\microsoft\visualstudio\16.0_d79d5920\devenv.exe.config
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 158 stepping 9, genuineintel
@set processor_level=6
@set processor_revision=9e09
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules;c:\program files\intel\
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_installdir_vs2017=c:\program files (x86)\microsoft visual studio\2017\community
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\community
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\5.0.103\sdks
@set servicehublogsessionkey=6bc2a4d7
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\coolie\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\coolie\appdata\local\temp
@set ucrtversion=10.0.19041.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=new-dev-pc
@set userdomain_roamingprofile=new-dev-pc
@set username=coolie
@set userprofile=c:\users\coolie
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\community\vc\redist\msvc\14.28.29325\
@set vctoolsversion=14.28.29333
@set visualstudiodir=v:\steve\mydocs\visual studio 2019
@set visualstudioedition=microsoft visual studio community 2019
@set visualstudioversion=16.0
@set vs100comntools=c:\program files (x86)\microsoft visual studio 10.0\common7\tools\
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vs80comntools=c:\program files (x86)\microsoft visual studio 8-2015\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=16.8.5
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\
@set vslang=1033
@set vssdk140install=c:\program files (x86)\microsoft visual studio 14.0\vssdk\
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.19041.0;c:\program files (x86)\windows kits\10\references\10.0.19041.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.19041.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.19041.0\
@set windowssdkversion=10.0.19041.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set zes_enable_sysman=1
@set __compat_layer=runasadmin
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.28.29333\bin\hostx86\x86;c:\program files (x86)\windows kits\10\bin\10.0.19041.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\debugging tools for windows (x64)\;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\putty\;c:\program files (x86)\microsoft sql server\90\tools\binn\;c:\nasm\;c:\program files (x86)\windows live\shared;v:\steve\mydocs\openssl-win64\bin;c:\windows\system32\openssh\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files\microsoft windows performance toolkit\;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\crucial\crucial storage executive;c:\llvm\bin;c:\program files\microsoft\web platform installer\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\git\cmd;c:\program files\cmake\bin;c:\program files\dotnet\;c:\users\coolie\appdata\local\microsoft\windowsapps;c:\program files (x86)\windows kits\10\debuggers;c:\program files (x86)\dr. memory\bin\;c:\users\coolie\appdata\local\programs\fiddler;c:\users\coolie\appdata\local\microsoft\windowsapps;c:\users\coolie\appdata\local\programs\python\python36;c:\users\coolie\.dotnet\tools
@set __vscmd_script_err_count=0

@call "cl.exe" @"C:\Users\coolie\Desktop\Code\PowerSDR-Thetis-G7KLJ\Project Files\Source\wdsp\delay.c.PVS-Studio.preprocess.cmd.rsp" 2>&1